---
root: true

parserOptions:
  ecmaVersion: 9

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - prettier
  - prettier/react
  - plugin:import/errors
  - plugin:import/warnings

plugins:
  - react
  - import
  - prettier

settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']

env:
  es6: true
  browser: true
  node: true

rules:
  import/no-extraneous-dependencies: off
  eol-last: ['error', 'always']
  import/extensions: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off

overrides:
  # typescript
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ['./tsconfig.json']
    extends:
      # - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - prettier/@typescript-eslint
      - plugin:import/typescript
    plugins:
      - '@typescript-eslint'
    rules:
      '@typescript-eslint/member-delimiter-style': off
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-unused-vars': warn
  # jest overrides
  - files: ['**/*.spec.ts']
    extends:
      - plugin:jest/recommended
      - plugin:chai-friendly/recommended
    plugins:
      - jest
    env:
      jest: true
      jest/globals: true
    rules:
      jest/no-disabled-tests: warn
      jest/no-focused-tests: error
      jest/no-identical-title: error
      jest/prefer-to-have-length: warn
      jest/valid-expect: error
