---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: ['./tsconfig.json']

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - airbnb
  - plugin:prettier/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:chai-friendly/recommended

plugins:
  - react
  - react-hooks
  - import
  - jest
  - prettier
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.tsx']

env:
  es6: true
  browser: true
  node: true
  jest: true
  jest/globals: true

rules:
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/no-unsafe-call': off
  import/no-extraneous-dependencies: off
  eol-last: ['error', 'always']
  import/extensions: off
  import/default: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  react/no-unused-prop-types: warn
  object-shorthand: warn
  # no-debugger: warn
