---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: ['./tsconfig.json']
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - airbnb
  - prettier
  - prettier/react
  - prettier/@typescript-eslint

plugins:
  - react
  - import
  - jest
  - prettier
  - '@typescript-eslint'
  - unused-imports

settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']

env:
  es6: true
  browser: true
  node: true
  jasmine: true
  jest: true
  jest/globals: true

rules:
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-explicit-any': off
  import/extensions: off
  no-shadow: 0
  no-unused-vars: 0
  prefer-destructuring: 0
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  unused-imports/no-unused-imports: error
  unused-imports/no-unused-imports-ts: error
  unused-imports/no-unused-vars: error
  unused-imports/no-unused-vars-ts: error
