---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: ['./tsconfig.json']
  ecmaVersion: 2021

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - airbnb
  - plugin:prettier/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:chai-friendly/recommended

plugins:
  - react
  - react-hooks
  - import
  - jest
  - prettier
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.tsx']
      paths: src

env:
  es6: true
  browser: true
  node: true
  jest: true
  jest/globals: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-debugger': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-param-reassign': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/restrict-template-expressions': off
  # this next line is disabling all the warnings about non typed stuff:
  eol-last: [error, always]
  func-style: [warn, expression]
  import/default: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-debugger: warn
  no-fallthrough: warn
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor: [memo]
  no-shadow: 0
  no-unused-vars: 0
  no-use-before-define: 0
  object-shorthand: warn
  prefer-destructuring: 0
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/no-unused-prop-types: warn
  react/require-default-props: off
