---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  project: ['./tsconfig.json']
  ecmaVersion: 2021

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jest/recommended
  - airbnb
  - plugin:prettier/recommended
  - prettier/react
  # - prettier/@typescript-eslint
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

plugins:
  - react
  - react-hooks
  - import
  - jest
  - '@typescript-eslint'

settings:
  import/resolver:
    node:
      extensions: ['.js', '.ts', '.tsx']
      paths: [src]

env:
  es6: true
  browser: true
  node: true
  jest: true
  jest/globals: true

rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/member-delimiter-style': off
  '@typescript-eslint/no-debugger': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-floating-promises': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-argument': warn
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-return': off
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/restrict-template-expressions': off
  comma-dangle: [error, only-multiline]
  curly: [error, multi-or-nest]
  eol-last: [error, always]
  func-names: off
  import/default: off
  import/extensions: off
  import/no-extraneous-dependencies: off
  no-case-declarations: off
  no-debugger: warn
  no-fallthrough: warn
  no-param-reassign:
    - warn
    - props: true
      ignorePropertyModificationsFor:
        - memo
  no-return-assign: off
  no-shadow: off
  no-unused-vars: warn
  no-use-before-define: off
  object-shorthand: error
  prefer-destructuring: warn
  prefer-template: error
  react/destructuring-assignment: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/no-unused-prop-types: warn
  react/require-default-props: off
