version: '3.4'

services:
  web:
    image: otomi/console:${WEB_TAG:-master}
    container_name: web
    expose:
      - 8080
    ports:
      - 8081:80
    volumes:
      - $PWD/nginx/nginx.tmpl:/app/nginx.tmpl
      - $PWD/nginx/run.sh:/app/run.sh
      - $PWD/nginx/session.lua:/app/session.lua
      - $PWD/nginx/services.lua:/app/services.lua
    environment:
      CORE: ${CORE}
      CORE_VERSION: ${CORE_VERSION:-master}
      CLUSTER: ${CLUSTER}
      CLUSTERS: ${CLUSTERS}
      TEAM_SERVICES: ${TEAM_SERVICES}
      TEAMS: ${TEAMS}
