version: '3.4'

services:
  api:
    container_name: api
    image: eu.gcr.io/otomi-cloud/otomi-api:${API_TAG:-master}
    command: sh -c 'node dist/app.js'
    user: ${USER_ID}:${GROUP_ID}
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - $PWD/core.yaml:/etc/otomi/core.yaml
      - tmp:/tmp
    environment:
      TOOLS_HOST: tools
      GIT_LOCAL_PATH: /tmp/otomi-values
    env_file:
      - compose/.env

  tools:
    depends_on:
      - api
    container_name: tools
    image: otomi/core:${TOOLS_TAG:-master}
    user: ${USER_ID}:${GROUP_ID}
    command: sh -c 'binzx/otomi server -vv'
    expose:
      - 17771
    ports:
      - 17771:17771
    volumes:
      - tmp:/tmp
    environment:
      ENV_DIR: /tmp/otomi-values
    env_file:
      - compose/.env

volumes:
  tmp:
    driver: local
    driver_opts:
      type: None
      device: /tmp
      o: bind
