version: '3.4'

services:
  web:
    build:
      context: .
      target: prod
    command: exec openresty -g 'daemon off;'
    environment:
      API_BASE_URL: 'api:8080'
      WEB_BASE_URL: 'web:8081'
