version: '3.4'

services:
  api:
    container_name: api
    image: eu.gcr.io/otomi-cloud/otomi-api:${API_TAG:-master}
    command: sh -c 'node dist/app.js'
    user: ${USER_ID}:${GROUP_ID}
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - $PWD/docker-compose/core.yaml:/etc/otomi/core.yaml
      - tmp:/tmp
    environment:
      TOOLS_HOST: tools
      CLUSTER_ID: ${CLUSTER_ID:-google/dev}
      CLUSTER_APISERVER: ${CLUSTER_APISERVER}
      DISABLE_SYNC: ${DISABLE_SYNC:-true}
      GIT_LOCAL_PATH: /tmp/otomi-values
      GIT_REPO_URL: ${GIT_REPO_URL:-gitea.dev.eks.otomi.cloud/otomi/values}
      GIT_SSL_NO_VERIFY: 'true'
      GIT_BRANCH: ${GIT_BRANCH:-main}
      GIT_USER: ${GIT_USER:-otomi-admin}
      GIT_EMAIL: ${GIT_EMAIL:-not@us.ed}
      GIT_PASSWORD: ${GIT_PASSWORD:-bladibla}

  tools:
    depends_on:
      - api
    container_name: tools
    image: otomi/core:${TOOLS_TAG:-master}
    user: ${USER_ID}:${GROUP_ID}
    command: sh -c 'binzx/otomi server -vv'
    expose:
      - 17771
    ports:
      - 17771:17771
    volumes:
      - tmp:/tmp
    environment:
      ENV_DIR: /tmp/otomi-values
      GCLOUD_SERVICE_KEY: ${GCLOUD_SERVICE_KEY}

volumes:
  tmp:
    driver: local
    driver_opts:
      type: None
      device: /tmp
      o: bind
