version: '3.4'

services:
  web:
    build: .
    image: eu.gcr.io/otomi-cloud/otomi-stack-web:${WEB_TAG:-latest}
    expose:
      - 80
  proxy:
    image: nginx:latest
    ports:
      - 3001:80
    expose:
      - 80
    depends_on:
      - api
      - web
    volumes:
      - docker-compose/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  e2e:
    image: otomi/cypress:latest
    working_dir: /app
    command: env
    volumes:
      - ./:/app
      - '/app/node_modules'
    environment:
      - PERCY_TOKEN=${PERCY_TOKEN}
      - CYPRESS_baseUrl=http://proxy:80
    depends_on:
      - proxy
