version: '3.4'

volumes:
  npm-cache:
    external: false
services:
  web:
    build:
      context: ../
      target: dev
    image: web-dev
    command: npm run dev:docker
    volumes:
      - ./:/app
      - .npm:/root/.npm
    environment:
      PUBLIC_URL: 'kubernetes.internal.local:8080'
    ports:
      - 3000:3000
    expose:
      - 3000
