version: '3.4'

services:
  web:
    build:
      context: .
      target: dev
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    image: otomi/console:${WEB_TAG:-master}
    container_name: web
    command: npm run dev:docker
    volumes:
      - ./:/app
      - .npm:/root/.npm
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      API_BASE_URL: 'kubernetes.docker.internal:8080'
