version: '3.4'

services:
  api:
    image: eu.gcr.io/otomi-cloud/otomi-stack-api:${API_TAG:-latest}
    env_file: './.env.api'
    expose:
      - 8080
    volumes:
      - ./core.yaml:/etc/otomi/core.yaml
