version: '3.4'

services:
  web:
    image: eu.gcr.io/otomi-cloud/otomi-stack-web:${WEB_TAG:-latest}
    expose:
      - 80
  proxy:
    image: nginx:latest
    ports:
      - 3001:80
    expose:
      - 80
    depends_on:
      - api
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  e2e:
    image: eu.gcr.io/otomi-cloud/otomi-stack-e2e:latest # @todo add stuff to and use otomi/cypress:latest
    working_dir: /app
    volumes:
      - ../:/app
      - '/app/node_modules'
    environment:
      - CYPRESS_baseUrl=http://proxy:80
    depends_on:
      - proxy
