version: '3.4'

services:
  web:
    build:
      context: ../
      target: dev
    # image: web-dev
    command: npm run dev
    volumes:
      # we only mount our src folder into the container for hotreload to work
      # if we would mount the entire ./builder into the container that will interfere with locally built node _modules
      - ../:/app
      - '/app/node_modules'
    environment:
      PUBLIC_URL: 'api:8080'
    ports:
      - 3000:3000
    expose:
      - 3000
