name: Build and publish Docker
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  REG: eu.gcr.io
  REPO: otomi-cloud/otomi-stack-web
  E2E_IMG: eu.gcr.io/otomi-cloud/otomi-stack-e2e:latest
  GIT_USER: redkubesbot
  GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  PW: '${{ secrets.DOCKER_PASSWORD }}'

jobs:
  build-test-push-release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: |
          env
          P=$(env | grep PW)
          echo $P
      - name: Set env
        run: |
          tag=$(echo $(basename $GITHUB_REF))
          echo "Creating tag: $tag"
          echo ::set-env name=TAG::$tag
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI tests, image build and push tag for master or branch
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: _json_key
          password: '${{ secrets.DOCKER_PASSWORD }}'
          registry: ${{ env.REG }}
          image_name: ${{ env.REPO }}
          image_tag: ${{ env.TAG }}
      - name: Docker login
        run: docker login -u _json_key -p '${{ secrets.DOCKER_PASSWORD }}' $REG
      - name: Run e2e
        if: "github.ref == 'refs/heads/master'"
        run: |
          docker pull $E2E_IMG
          container_id=$(docker create $E2E_IMG)  # returns container ID
          docker cp $container_id:docker-compose.yml docker-compose.yml
          docker cp $container_id:core.yaml core.yaml
          docker cp $container_id:.env.api .env.api
          docker cp $container_id:.env.web .env.web
          docker cp $container_id:nginx.conf nginx.conf
          docker rm $container_id
          WEB_TAG=master docker-compose up --exit-code-from e2e
          cd -
      - if: "contains(github.event.head_commit.message, 'chore(release)')"
        name: Tag and release
        run: |
          RELEASE_TAG=v${COMMIT_MSG#* }
          echo "Releasing $REG/$REPO:$RELEASE_TAG"
          docker tag $REG/$REPO:$TAG $REG/$REPO:$RELEASE_TAG
          docker push $REG/$REPO:$RELEASE_TAG
          git config --global user.email "$GIT_USER@users.noreply.github.com"
          git config --global user.name $GIT_USER
          echo "machine github.com login $GIT_USER password $GIT_PASSWORD" > ~/.netrc
          git tag -am "$COMMIT_MSG" $RELEASE_TAG && git push --follow-tags origin master
          echo "Also tagging and pushing $REG/$REPO:latest"
          docker tag $REG/$REPO:$TAG $REG/$REPO:latest
          docker push $REG/$REPO:latest
