name: Build and publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # used for pulling previous image as cache:
      - uses: azure/docker-login@v1
        with:
          login-server: eu.gcr.io
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          docker pull eu.gcr.io/otomi-cloud/otomi-stack-web
      - uses: docker
        with:
          image: 'Dockerfile'
          args: 'build .'
      - name: Publish to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: eu.gcr.io/otomi-cloud/otomi-stack-web
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true
