name: Build and publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        uses: actions/docker/cli@master
        with:
          args: 'login -u _json_key -p ${{ secrets.DOCKER_PASSWORD }} eu.gcr.io'
      - name: Pull from registry as cache
        uses: actions/docker/cli@master
        with:
          args: 'pull eu.gcr.io/otomi-cloud/otomi-stack-web'
      - name: CI tests and image build
        uses: actions/docker/cli@master
        with:
          args: 'build -t eu.gcr.io/otomi-cloud/otomi-stack-web .'
      - name: Publish only tags to registry
        uses: docker/build-push-action@v1
        if: contains(github.ref, 'refs/tags/v')
        with:
          registry: eu.gcr.io
          repository: otomi-cloud/otomi-stack-web
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
