name: Build and publish Docker
on: [push]
env:
  REG: eu.gcr.io
  REPO: otomi-cloud/otomi-stack-web
jobs:
  publish:
    runs-on: ubuntu-latest
    # skip also when release chore gets pushed to master, as we expect it to be built upon the tag release
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u _json_key -p '${{ secrets.DOCKER_PASSWORD }}' $REG
      - name: Pull from registry as cache
        run: 'docker pull $REG/$REPO:latest || true'
      - name: CI tests and image build
        run: 'docker build .'
      - name: Publish latest
        if: "github.ref != 'master' || !contains(github.event.head_commit.message, 'chore(release)')"
        uses: docker/build-push-action@v1
        with:
          registry: ${{ env.REG }}
          repository: ${{ env.REPO }}
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
