name: Build and publish Docker
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
env:
  COMMIT_MSG: ${{ github.event.head_commit.message }}
  REG: eu.gcr.io
  REPO: otomi-cloud/otomi-stack-web
jobs:
  build-test-push-release:
    if: "!contains(github.event.head_commit.message, 'ci skip') && !startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          tag=$(echo $(basename $GITHUB_REF))
          echo "Creating tag: $tag"
          echo ::set-env name=TAG::$tag
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI tests, image build and push tag for master or branch
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: _json_key
          password: '${{ secrets.DOCKER_PASSWORD }}'
          registry: ${{ env.REG }}
          image_name: ${{ env.REPO }}
          image_tag: ${{ env.TAG }}
      - name: Docker login
        run: docker login -u _json_key -p '${{ secrets.DOCKER_PASSWORD }}' $REG
      - name: Push tag 'latest'
        run: |
          docker tag $REG/$REPO:$TAG $REG/$REPO:latest
          docker push $REG/$REPO:latest
      - if: "contains(github.event.head_commit.message, 'chore(release)')"
        name: Tag and release
        run: |
          RELEASE_TAG=v${COMMIT_MSG#* }
          echo "Releasing $REG/$REPO:$RELEASE_TAG"
          docker tag $REG/$REPO:$TAG $REG/$REPO:$RELEASE_TAG
          docker push $REG/$REPO:$RELEASE_TAG
          git tag -am "$COMMIT_MSG" $RELEASE_TAG && git push --follow-tags origin master
