name: Build and publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: 'docker login -u _json_key -p "${{ secrets.DOCKER_PASSWORD }}" eu.gcr.io'
      - name: Pull from registry as cache
        run: 'docker pull eu.gcr.io/otomi-cloud/otomi-stack-web:latest | true'
      - name: CI tests and image build
        run: 'docker build .'
      - name: Publish latest
        uses: docker/build-push-action@v1
        with:
          registry: eu.gcr.io
          repository: otomi-cloud/otomi-stack-web
          username: _json_key
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_ref: true
