name: Build and publish Docker
on: [push]
env:
  REF: ${{ github.ref }}
  REG: eu.gcr.io
  REPO: otomi-cloud/otomi-stack-web
jobs:
  build:
    runs-on: ubuntu-latest
    # skip also when release chore gets pushed to master, as we expect it to be built upon the tag release
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: CI tests and image build
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: _json_key
          password: '${{ secrets.DOCKER_PASSWORD }}'
          registry: ${{ env.REG }}
          image_name: ${{ env.REPO }}
          image_tag: ${{ github.ref }}
          push_git_tag: true
