name: Build and publish Docker
on: [push]
env:
  REF: ${{ github.ref }}
  REG: eu.gcr.io
  REPO: otomi-cloud/otomi-stack-web
jobs:
  build-test-push:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Set Env
        run: |
          tag=$(echo $(basename $GITHUB_REF))
          cacheTag=$tag
          [[ $GITHUB_REF == *"refs/tags/"* ]] && cacheTag=master
          echo "Creating tag: $tag"
          echo "Using cache tag: $cacheTag"
          echo ::set-env name=TAG::$tag
          echo ::set-env name=CACHE_TAG::$cacheTag
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u _json_key -p '${{ secrets.DOCKER_PASSWORD }}' $REG
      - name: Pull from registry as cache
        run: 'docker pull $REG/$REPO:$CACHE_TAG || true'
      - name: Docker build
        run: docker build $REG/$REPO:$TAG .
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: 'Push tag for dev/caching'
        run: docker push $REG/$REPO:$CACHE_TAG
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Tag and release
        run: |
          docker tag $REG/$REPO:$TAG $REG/$REPO:latest
          docker push $REG/$REPO:$TAG $REG/$REPO:latest
